name: Pipeline CI - Spring Boot

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Configurar o Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: 3. Dar permissão de execução para o gradlew
        run: chmod +x gradlew

      - name: 4. Compilar o projeto (Build)
        run: ./gradlew clean build -x test

      - name: 5. Executar os Testes Unitários
        run: ./gradlew test